### ISSUE TITLE
Results not saved to HDF when failed samples are present.

### ISSUE THREAD

**Issue by Paulie14** [GeoMop/MLMC#90]
I have problem when collecting the results to HDF when there are some failed results
My simulation ends with an exception (e.g. solver did not converge, so there are no results to extract..).
Later the collected results are not written to HDF (only zeros are visible).
I receive this error:
```
Traceback (most recent call last):
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/wgc2020_model/process.py", line 344, in <module>
    pr = WGC2020_Process()
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/wgc2020_model/process.py", line 30, in __init__
    super(WGC2020_Process, self).__init__()
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/tool/process_base.py", line 22, in __init__
    self.run()
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/wgc2020_model/process.py", line 48, in run
    self.generate_jobs(sampler, n_samples=n_samples, renew=renew)
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/wgc2020_model/process.py", line 159, in generate_jobs
    sampler.ask_sampling_pool_for_samples(sleep=self.sample_sleep, timeout=self.sample_timeout)
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/sampler.py", line 168, in ask_sampling_pool_for_samples
    self._store_samples(successful_samples, failed_samples, n_ops)
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/sampler.py", line 184, in _store_samples
    self.sample_storage.save_samples(successful_samples, failed_samples)
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/sample_storage_hdf.py", line 149, in save_samples
    self._save_succesful(successful)
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/sample_storage_hdf.py", line 155, in _save_succesful
    self._level_groups[level].append_successful(np.array(samples))
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/tool/hdf5.py", line 335, in append_successful
    self._append_dataset(d_name, [val for val in values])
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/MLMC/src/mlmc/tool/hdf5.py", line 357, in _append_dataset
    dataset[-len(values):] = values
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/paulie/docker_flow123d/WGC2020-THM-MC/mlmc_random_frac/env/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 647, in __setitem__
    raise TypeError("When writing to array types, last N dimensions have to match (got %s, but should be %s)" % (valshp, shp,))
TypeError: When writing to array types, last N dimensions have to match (got (61, 2), but should be (2, 124))
```

**Comment by jbrezmorf** [comment]
@martinspetlik  Seems like there is sort of transposed array, but still 61 != 124. Please, try to find the source of the problem with @Paulie14

**Comment by Paulie14** [comment]
Problem "solved". Sorry - my bad.

There were several samples, which were killed by reaching walltime in pbs process.
Since the simulation is time dependent, several time steps were already computed and results written to files.
I detect "failed" computation only by presence of result files and checking solver convergence - these were ok, but not all time steps were computed. Therefore the collected vector of time values was shorter resulting in the dimension mismatch.

**Comment by Paulie14** [comment]
Question remains, whether we can detect reaching walltime somewhere on the sampler level, or it is supposed to be detected by the simulation - when extracting results (e.g. look for error in log, or somehow checking the expected vector length directly..).

**Comment by Paulie14** [comment]
Summary - the shape of data returned from the simulation should be checked against the expected result format.
Next, the result format should NOT be static function, it should be able to configurate the time axis externally.
